### ISSUE TITLE
[issue ] Can't run your mod # 2

### ISSUE THREAD

**Issue by Scorpions95** [shedaniel/RoughlyEnoughItems#1004]
### What happened?

REI doesnt run, i mean i can't activate it, download all needed mods from here
https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items
https://i.gyazo.com/19b97766528f2880e9ec72abc0729480.png
i clear this errors https://i.imgur.com/KpY1GRg.png
but can't activate it again
i got all these mod and can't use mod
what i need to do to activate it?

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
there is no error log
```

### Anything else?

Can't activate mod

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Hey, thanks for submitting an issue to RoughlyEnoughItems. Your issue lacks the necessary logs to help trace the issue down, while you have incorrectly declared that you have done so, which is why I am closing the issue.

Please create a new issue with the correct logs, you should upload the `latest.log` from the `.minecraft/logs` folder that is next to your `mods` folder.

Development time is limited, please make sure you have the sufficient information.
