### ISSUE TITLE
[Bug] Unable to Backspace in Search Bar if recipe windows are open

### ISSUE THREAD

**Issue by MuteTiefling** [shedaniel/RoughlyEnoughItems#1081]
### What happened?

1. Open REI
2. Check Recipes for any item
3. Type a new search
4. Attempt to clear that search
5. Note that it has to 'back up' through all open recipe panes first before Backspace will delete characters

Mod Versions
REI: RoughlyEnoughItems-9.1.530
Forge: 41.1.0

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://gist.github.com/MuteTiefling/db7cdb96da95196376693327b9734fc4
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by SirChamomile** [comment]
Are we sure this is a bug and not a feature?

**Comment by shedaniel** [comment]
This is a bug

**Comment by embeddedt** [comment]
This also affects 1.18 on Fabric/Quilt.

**Comment by Abalieno** [comment]
It IS a bug, not a feature.

The reason is that pressing "backspace" goes back in recipes even when the search bar is in focus with the cursor blinking.

So let's say you're browsing through several recipes. You won't be able to write in the search bar. You have to exit the recipes entirely.

The whole problem is handling it differently when you're focusing on the search bar, or not. If I'm browsing through recipes the search bar is NOT in focus, or if I press "R" rather than looking up a recipe for the item it would write R on the search bar.

**Comment by Abalieno** [comment]
Adding to this without opening an issue for something more trivial: if you move the search bar to the center, big tooltips end up rendering behind the search bar, rather than one layer above.

**Comment by Raidobw2** [comment]
Just adding onto other comments as well, for people coming across this issue, you can work around it by right-clicking the search box instead of using backspace. Right clicks clear the search box completely, allowing you to type another search term

**Comment by Raidobw2** [comment]
Awesome, thank you for the fix!
