### ISSUE TITLE
Search bar not working [1.19]

### ISSUE THREAD

**Issue by bluejuju** [shedaniel/RoughlyEnoughItems#1093]
### What happened?

So I'm playing on a modpack on curseforge called [The Unoffical OriginSMP](https://www.curseforge.com/minecraft/modpacks/the-unofficial-origin-smp)
and I can't search items with REI. The Modpack has a server and it works for everyone on that server and they play with the same modpack as I am but it won't work for me somehow. I reinstalled the modpack, reinstalled the .jar REI file and replaced it with the same update and even put in the newer one Fabric 1.19-1.19.2 v9.1.530. 
Nothing worked for me but everything for the others.
I saw that problems could be because of the mod "Extra Generators" but that doesn't explain, why it works for everyone but me.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Got nothing really, checked both and nothing relevant really. If needed, I can still post them if asked for.
```

### Anything else?

https://www.curseforge.com/minecraft/modpacks/the-unofficial-origin-smp

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Hey, thanks for submitting an issue to RoughlyEnoughItems. Your issue lacks the necessary logs to help trace the issue down, while you have incorrectly declared that you have done so, which is why I am closing the issue.

Please create a new issue with the correct logs, you should upload the `latest.log` from the `.minecraft/logs` folder that is next to your `mods` folder.

Development time is limited, please make sure you have the sufficient information.
