### ISSUE TITLE
[Bug] No Mekanism Recipes

### ISSUE THREAD

**Issue by wuggyfoot** [shedaniel/RoughlyEnoughItems#1113]
### What happened?

There are no recipes for processes inside of Mekanism machines. I expected there to be recipes.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://drive.google.com/file/d/1XR_pG4A_sBddYq6ZwdKp2WzuO5rBeLSM/view?usp=sharing

log download xd
```

### Anything else?

This is for 1.19.2 REI 9.1.530 Mekanism version 10.3.3.470

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Hey, thanks for submitting an issue to RoughlyEnoughItems. Your issue contains the necessary logs **but they are not uploaded directly or to GitHub gists**, while you have incorrectly declared that you have done so, which is why I am closing the issue.

Please create a new issue with the correct uploads.

Development time is limited, please make sure you have the sufficient information.
