### ISSUE TITLE
search bar

### ISSUE THREAD

**Issue by grimlock485** [shedaniel/RoughlyEnoughItems#1117]
### What happened?

im using the 1.19 version and it was working fine up until now but then the search bar stopped working and it just says catching search and never gives me the results i tried uninstalling it but it still did not work 

### What mod loaders are you seeing the problem on?

Fabric, Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
it doesnt show any log
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Hey, thanks for submitting an issue to RoughlyEnoughItems. Your issue lacks the necessary logs to help trace the issue down, while you have incorrectly declared that you have done so, which is why I am closing the issue.

Please create a new issue with the correct logs, you should upload the `latest.log` from the `.minecraft/logs` folder that is next to your `mods` folder.

Development time is limited, please make sure you have the sufficient information.

**Comment by slimygs** [comment]
This is also happening to my rei menu search bar. Stuck at 67% and unusable until it fully loads. It’s happened twice and I’m not sure what fixed it the first time. There was no logs the game reported due to this.
