### ISSUE TITLE
[Bug] Crash 1.18.2 with Journey Map latest version

### ISSUE THREAD

**Issue by TerraSpecOp** [shedaniel/RoughlyEnoughItems#1133]
### What happened?

Minecraft is crashing at startup

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Mod File: /C:/Games/MultiMC/instances/1.18.2 Test/.minecraft/mods/journeymap-1.18.2-5.9.0beta2-forge.jar
	Failure message: Journeymap (journeymap) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 5.9.0beta2
	Mod Issue URL: https://github.com/TeamJM/journeymap/issues
	Exception message: java.lang.AssertionError: REI Internals have not been initialized!
```

### Anything else?

With the older version 8.3.529 of REI everything works fine.
Tested also with  the newest REI Plugin Comp. - same result

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Hey, thanks for submitting an issue to RoughlyEnoughItems. Your issue lacks the necessary logs to help trace the issue down, while you have incorrectly declared that you have done so, which is why I am closing the issue.

Please create a new issue with the correct logs, you should upload the `latest.log` from the `.minecraft/logs` folder that is next to your `mods` folder.

Development time is limited, please make sure you have the sufficient information.
