### ISSUE TITLE
[Feature] Enable/Disable REI

### ISSUE THREAD

**Issue by thimblebird** [shedaniel/RoughlyEnoughItems#1255]
### What is your feature request?

a toggle to enable/disable REI as a whole would be neat for modpack developers; so people can opt-in/out to use REI while the modpack still has REI installed

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by rozbrajaczpoziomow** [comment]
Well there's a keybind to disable the gui in your inventory, I think Ctrl+O by default

**Comment by thimblebird** [comment]
> Well there's a keybind to disable the gui in your inventory, I think Ctrl+O by default

so in theory i could simulate the press of that keybind to disable the gui by default? otherwise the issue/suggestion still stands

//e: i'm actually talking about a button in the config interface in the game that represents the corresponding option set in the config file

**Comment by shedaniel** [comment]
Huh? I don’t think this is that useful, your use case is quite niche, first time this is requested in 4 years anyways

**Comment by thimblebird** [comment]
People also just use default configs in modpacks and call it a day... You already have a keybind, which someone at some point requested or that you wanted to have; how is that different from a visual representation of said feature?

**Comment by shedaniel** [comment]
Then how is telling the user to just uninstall REI different then telling the user to disable/enable REI. You either ship it by default or don't, same as you either disable it or enable it by default.

**Comment by thimblebird** [comment]
One might want to try it out for the first time; then doesn't like it and wants to disable it, but it's in a modpack. Doesn't know the keybind and gets frustrated. Isn't tech-savvy and doesn't know about config files and folders.

You assume a lot; this is not about being a niche request, it's about accessibility for players. You can't say "let's not build a ramp on these stairs, I don't really see people in wheelchairs nowadays anyways". Or, you can, but... Yeah.

Again, how is the keybind different from a visual toggle button? 🤔

**Comment by shedaniel** [comment]
Well, where do I put the button?

If I add it in the config screen, then do the users know how to find the ModMenu to turn it back on? Also, ModMenu isn't a requirement to using REI, what if the users don't have ModMenu installed, don't know about the keybind, then turn off REI in the config screen?

Ctrl+O is the standard keybind for \*EI mods for ages, and I don't feel like adding a prominent button on the screen **just** to toggle REI.

**Comment by thimblebird** [comment]
Modpack curators do exactly this: make the lives of people easier with QoL mods like REI, then adding a mod for disabling the recipe book button in the inventory... In this case, they would install something like ModMenu alongside REI.

It's more likely that users find a menu button than actually going into config files or searching for enable/disable in the keybinds section, I think.

I don't know about the button necessarily needing to be prominent, but it shouldn't be hidden behind a keybind either in my opinion...

//e: Maybe add it at the very end of the config screen and call it a day? 😅

**Comment by Xetaxheb** [comment]
@thimblebird  this is a silly request that just makes it confusing to deal with

as shedaniel said the keybind to toggle visibility has been standard forever 
and the idea that a new user is going to **find the config option at all** instead of seeing the keybind setting (because they should be setting their keybinds in the first place), **let alone if they disable it accidentally not understanding the config option** (which is its own whole can of worms)...

best case scenario the gear gui button stays around in the bottom right when rei is 'disabled' but personally I don't want it there

it sounds like you're blindly pushing for this option without really having good justification or understanding of it
and you already have your initial request anyway since you can just disable it in the config as pack creator with 		"overlayVisible": false,

You moved the goalposts from "I want to be able to disable REI by default as modpack creator" to "I want users to have a button to toggle REI instead of just keybind". The keybind is clearly labeled and again short of adding extra gui clutter when toggled off, it wouldn't be convenient to turn back on with that config button.

also REI already has disabling recipe book button and it really feels like you just haven't personally used REI enough to suggest changes. I wholly disagree that people will find a config button buried in REI before they find the clearly labeled keybind.

lastly, what's the point of putting REI in the **client** pack if you're just gonna disable it by default? it's clientsided and could be added by those who want it... except those who probably need it most are the ones who wouldn't know to enable it from disabled in the first place so it seems like a poor idea to disable anyway

**Comment by thimblebird** [comment]
@Xetaxheb I don't see this as a silly request at all. Having only a keybind for an option that affects the whole visual representation of the mod is bad user experience. Period.

Yes, I realize I haven't exactly explained the reasoning at all and, this being a discussion, getting new ideas and thoughts about the matter didn't help for people outside my brain. Apologies.

I am in the process of creating a mod for players to quickly switch their client configs. This means I can't switch from a profile with REI enabled to a profile with REI disabled without restarting the whole game.

This is the problem, roughly summarized. Now that I think about it, being relatively new to modding, it's probably "just" a (fair) case of REI not reloading the config on, say, executing `/reload` or joining a server, right?

I'm unsure of the default practices and if many mods even do that. My first thought when I created the issue wasn't about my mod at all (in fact I didn't even start it by then), which makes this a lot more confusing over the various comments for sure. My point and the original issue still stands, though.

What can I say, opinions change. I guess this is a won't fix issue and restarting the whole game when changing the config or knowing about the keybind is the only way?

**Comment by Xetaxheb** [comment]
> I am in the process of creating a mod for players to quickly switch their client configs. This means I can't switch from a profile with REI enabled to a profile with REI disabled without restarting the whole game.

You already can't do that without restarting the whole game... even if REI were to rescan the config or read on /reload, there are numerous mods that will not rescan changed configs and even some that will overwrite existing files on exit/world unload or /reload... plus just so many mechanics that don't work to even change in menu without restart.
**Hot swapping a config just doesn't do anything unless the mod is designed to be aware for it.**
But this is all not related to this issue or REI. 


> a toggle to enable/disable REI as a whole would be neat for modpack developers; so people can opt-in/out to use REI while the modpack still has REI installed

This exists, in the config as "overlayVisible".
> //e: i'm actually talking about a button in the config interface in the game that represents the corresponding option set in the config file

This isn't really useful since the keybind exists and would have no way to turn it back on without digging though a mod menu mod or... the keybind. Unless extra GUI is added when disabled. The obvious drawback to even implementing this is it removes the opportunity for the player to "learn" that REI can be toggled with keybind, so they may end up with no idea it exists.
> shipping with REI disabled in the first place

there's just... not a lot of point to this. the people who don't want REI can remove it (and save some overhead), the people who do want REI will be inconvenienced by it (or confused why it's not working), and the people who occasionally toggle REI should be aware of the keybind... and the new people oblivious to REI who would greatly benefit from it but never will from it being off by default.

-
edit: I've also just realized it's doubly pointless because the REI menu *shows you that you can keybind to toggle it anyway* so it's redundant and _less useful_ to have a toggle button in there

**Comment by shedaniel** [comment]
@thimblebird you are a developer, you may interact with the REI API to toggle it, add a button or something, I am not going to implement this in REI itself as with reasons above

REI is not designed with dynamic config reloading in mind because you can change all of it with code.

REIRuntime.getInstance().toggleOverlayVisible()
