### ISSUE TITLE
[Bug] Search breaks with Thermal

### ISSUE THREAD

**Issue by callmejay758** [shedaniel/RoughlyEnoughItems#1286]
### What happened?

When thermal is installed, search doesn't work when not using prefixes.

Mods used (Forge 1.19.2 - 43.2.0):
architectury-6.4.62
cofh_core-10.0.2.33
cloth-config-8.2.88
RoughlyEnoughItems-9.1.580
thermal_foundation-10.0.0.38

To reproduce:
1. Install Thermal (and dependencies) and REI.
2. Attempt to search without a prefix.
3. Observe that search results in unfiltered results.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
null
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Hey, thanks for submitting an issue to RoughlyEnoughItems. Your issue **lacks the necessary logs** to help trace the issue down, while you have incorrectly declared that you have done so, which is why I am closing the issue.

Please create a new issue with the correct logs, you should upload the `latest.log` from the `.minecraft/logs` folder that is next to your `mods` folder.

Development time is limited, please make sure you have the sufficient information.
