### ISSUE TITLE
[Bug] OptiFine Conflicts Problems with the search bar

### ISSUE THREAD

**Issue by CCjun6** [shedaniel/RoughlyEnoughItems#1387]
### What happened?

My client version is 1.19.4
And installed the latest version of and -MOD
But after entering the game, the search bar will not be able to enter any alphanumeric
You must click on any item in the synthesis bar to search. Please fix this BUG

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Conflicts and no logs
```

### Anything else?

![MOD](https://user-images.githubusercontent.com/128166019/228454510-770d47fa-ca9f-4b20-ac5a-5e5c3e980faf.png)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Nivo12** [comment]
Is there any update on this bug? I am still having that issue, some workaround works but shouldn't have to be the case. Should I use something other than optifine for the moment?

**Comment by TheRealWormbo** [comment]
Using Optifine is quite a bad idea in a modded context. Mod authors won't bother fixing the mess Optifine creates through its intrusive changes to how the game and rendering work, simply because Optifine is closed source and other mod authors have no easy way to figure out why things break.
If you're on Fabric, stick with the CaffeinMC suite of mods (Lithium, Sodium, Iris for shaders, etc.) and Starlight as a baseline. Also, you have both Optifine and Sodium in your mods folder – that will never work well together.

**Comment by shedaniel** [comment]
REI is not compatible with optifine. The general consensus with optifabric is that _if it works, it works, if it doesn't work, then too bad_.
Optifine is not open sourced, we cannot fix it.
