### ISSUE TITLE
[Bug] doesn't declare dependency on Architectury through fabric.mod.json

### ISSUE THREAD

**Issue by quat1024** [shedaniel/RoughlyEnoughItems#591]
Launching the game without Architectury installed opens a strange custom GUI halfway through the loading process, instead of failing-fast like basically every other mod I've ever used with a dependency. At least it's not a NoClassDefFound...?

![javaw_sJngJzJbxv](https://user-images.githubusercontent.com/2068021/127764603-4902270e-63d7-4050-abf2-17a1e25f00b4.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Additional context**
I was using `filebisect` to discover an unrelated mod-compat issue with a modpack. One of the inherent problems with a file bisecting tool is that it can accidentally remove dependencies of other mods. In this case it's really handy if the mod loader is able to fail early so I can identify the problem and fix it.

**Comment by shedaniel** [comment]
This is intended. This may not be preferred by other modders as this is not following the standards, but fabric’s error screen is unintuitive and convoluted, recent changes proposed by Player also does not fix the issues where players do not want to read black text on a white gui.

I prefer my blue text pointing to a download, red text indicating an error, and overall style to the minecraft gui theme. Users support for missing dependencies disappeared basically completely after I implemented this, the only people complaining about this screen were modders.

I have reconsidered many times if I would want to migrate back to fabric’s dependencies checker, but decided every single time that I would want to stay with this screen, if you have any opinions, please state them out, I am happy to listen.

**Comment by shedaniel** [comment]
A separate note that reacting doesn't help at all, if you have differing ideas than me, please say it out, or else, what do you expect me to do.

**Comment by shedaniel** [comment]
I am closing this issue as this is declined. Feel free to reply here if you have something else to say.

**Comment by luaxlab** [comment]
On 1.18.2 if Architectury API is missing, this leads to a crash.
Which is - in my eyes - more inconvinient than the black-on-white error screen that actually tells the problem.

**Comment by milkev** [comment]
When adding a bunch of mods, fabric will test if the dependencies of all mods that are installed, and compile them into a list. Its much more efficient to go through that single list once, rather than suddenly have another list pop up partway through the loading process.

I dont know what this popup was like in the past, but it doesnt seem convoluted at all anymore. It doesnt provide a direct link, but it says what mods are required, by what mod, and what recommended version to get.

**Comment by milkev** [comment]
one other big thing to consider is that if this ends up becoming a precedent for other mods to do (im surprised i havent seen more of this since REI is such a widely used mod) then you will have to go halfway through the loading process multiple times just to iron out all the missing dependencies that werent listed as dependencies, which can quickly become extremely time consuming

**Comment by shedaniel** [comment]
> one other big thing to consider is that if this ends up becoming a precedent for other mods to do (im surprised i havent seen more of this since REI is such a widely used mod) then you will have to go halfway through the loading process multiple times just to iron out all the missing dependencies that werent listed as dependencies, which can quickly become extremely time consuming

This is now an outdated issue, REI now shows the missing error screen almost immediately and you don’t need to wait for the game to load halfway.
