### ISSUE TITLE
[Bug]"REI Not Fully Initialised" Error on server side only

### ISSUE THREAD

**Issue by Lord1Locke** [shedaniel/RoughlyEnoughItems#622]
The modpack is 1.17.1 Euphoric Curiosity on the Fabric Launcher.

The issue is simple. Singleplayer works great. Multiplayer you can see the items but no recipes.  Says "REI Not Fully Initialised" at the bottom of REI. Message disappears upon hitting reload mods.

I can provide logs and screenshots if necessary, but i see that many say you have to reload mods to get REI to work upon entry to a server. I have reloaded and the only changed is the "not fully initialised" message goes away. Recipes are still not visible.

**Comment by AzureDoom** [comment]
@Lord1Locke this was due to any mod using NBTCrafting (my mods did but no longer do but Spice of Fabric does). This is an issue between NBTCrafting and REI. Euphoric Curiosity fixed this by removing Spice of Fabric and updating HWG and MCDoom to the latest versions which no longer use NBTCrafting for Patchouli books but instead use the newly discovered 1.17 crafting system for books.

**Comment by shedaniel** [comment]
This is not an issue **between** REI and NBTCrafting, this is purely an issue from NBTCrafting.
