### ISSUE TITLE
Item search crashes

### ISSUE THREAD

**Issue by Knito58** [shedaniel/RoughlyEnoughItems#67]
roughlyenoughitems: 2.7.9+build.94
Minecraft Version: 19w14b

I wanted to search for blocks of the trapexpansion mod and entered "@tr". I wanted to write more, but the game crashed.

[crash-2019-04-18_20.05.06-client.txt](https://pastebin.com/61gWubHy)

**Comment by Knito58** [comment]
... crash also works without the "@"...

**Comment by raulfpl** [comment]
Will also crash from the same error if you browse to the last page on the item list.

What causes the crash is trying to display the end of the list in a page, because the loop will not end at the end of the list. This causes `the java.lang.IndexOutOfBoundsException`

This issue is introduced by d7b09003852682c8c1562e0d73a9494cc54e7a6b

```java
for(int i = 0; i < getFullTotalSlotsPerPage(); i++) {
    if (j >= currentDisplayed.size())
        break;
    int x = startX + (i % width) * 18, y = startY + MathHelper.floor(i / width) * 18;
    if (!canBeFit(x, y, listArea))
        continue;
    j++;
```
Here, the `j++` would have to be inserted before the `if (j >= currentDisplayed.size()) break;`. Or else, it will cause the `the java.lang.IndexOutOfBoundsException` and crash.

**Comment by Knito58** [comment]
Many thanks for fixing!
