### ISSUE TITLE
[Feature] shortcut key for quick auto crafting

### ISSUE THREAD

**Issue by scarf005** [shedaniel/RoughlyEnoughItems#724]
**Describe the solution you'd like**
When copying recipe to workbench/crafting, there needs to be 2 steps; for example with this image taken from mod description:

![from curseforge](https://i.imgur.com/CDI8Ibi.png)
to create sugar you must
1. press `left click / r` at the sugar on the right panel to get recipe
2. press `+` button again to copy the recipe into crafting table

it would be really great to have direct keybinding so only 1 step would be needed. then the steps from above would be reduced to:

1. `ctrl + left click` at the sugar on the right panel to get first available recipe. 1 unit of sugar cane is into sent into crafting grid (assuming you have sugar canes)

**Additional context**
overall there might be two additional shortcut:
- `ctrl + LMB` to auto-craft a item from any possible recipe (same as pressing `+`)
- `shift + LMB` for auto-craft maximum possible items (similar to pressing `+` with shift key)

**Comment by magnus-ISU** [comment]
I would even prefer if you could have a shortcut to just instantly craft the item. REI is actually *worse* than the recipe book by default, but it could be better, because there are actually *three* steps that REI forces you to take. As it is though I am forced to use Mouse Wheelie's tacking this on to the recipe book because REI is so clunky. You have to

1. Left click recipe
2. Find and click on tiny little crappy + button
3. Click in crafting table to craft the item

Notice that if you want to do 3 (which you craft things in minecraft much more often than you look up their recipes) then you never ever want to stop this halfway. The only reason you would is if you want to single click items out of the crafting table, in which case you can just single click them out of REI much better if it actually implemented this.

So the obvious solution is making step 1 is the only one you have to do. Seeing a recipe without crafting it when it is possible to craft it should not even be the default behavior when clicking an item (at least if show-craftable-only is toggled on) but fragmenting settings like that is a bad idea and that's a big change to be making otherwise.

But there should at least be an option to make it so (when you have the items to craft something, and the bench is a crafting table since modded crafters and furnaces and stuff may require extra steps) left click instantly crafts the items, ctrl+left click shows the recipe.

**Comment by shedaniel** [comment]
There are a few options that we can go with:

Option 1: Don't add this

Option 2:
Ctrl+Left for quick craft
Ctrl+Right for quick craft a stack

This mimics the cheating mode because left clicking a stack on cheat mode is 1 and right clicking is a stack

Option 3:
Ctrl+Left for quick craft
Ctrl+Shift+Left for quick craft a stack

This mimics the existing + button as you press shift to craft a stack

Additionally, we can add a keybind to do this **on top** of the above options:
Key for quick craft
Shift+Key for quick craft a stack

**Comment by scarf005** [comment]
> Option 2:
> Ctrl+Left for quick craft
> Ctrl+Right for quick craft a stack
> 
> This mimics the cheating mode because left clicking a stack on cheat mode is 1 and right clicking is a stack

this seems to be the best option since it seamlessly integrate similar functionality with 'cheat mode`. then there could be options for:
- modifier for auto crafting (above:  `ctrl`)
- choose whether 'craft' the item or only move ingredients to crafting grid

**Comment by shedaniel** [comment]
We can't craft the item for you, that's too hard to do unfortunately, but yes

**Comment by shedaniel** [comment]
This is now a feature in REI! Thanks for suggesting!

Available on REI 6.4 and 7.2
