### ISSUE TITLE
[Bug] REI breaks with fabric loader 0.13.0

### ISSUE THREAD

**Issue by celophys** [shedaniel/RoughlyEnoughItems#756]
### What happened?

I just updated fabric and now jei don't shows in the invetory

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [x] Others

**Comment by Waoweens** [comment]
I am also having this issue. Works fine on Fabric Loader 0.12.12 but doesn't display on 0.13.0

[latest.log](https://gist.github.com/Waoweens/751373d20a9ffc1bf3b9b5c90c35ddfb)
[rei.log](https://gist.github.com/Waoweens/1422ffdc433a2a566601f44c21f6645a)

Fabric API 0.46.4+1.18
REI 7.2.418
Architectury 3.6.15
Cloth Config 6.1.48

![2022-02-03_11 29 03](https://user-images.githubusercontent.com/30313089/152281485-113b1cb2-fdd6-4e88-9050-bc7d8c024b9e.png)

**Comment by shedaniel** [comment]
Thanks for reporting! I know this is a serious issue and it would need some time to fix this as I would have to first identify this weird issue, and see the range of REI versions affected. Please bare with me while this is being worked on, thanks!

**Comment by yesn0t** [comment]
if it helps i tried REI 7.2.418, 7.2416, and 7.2.409 with fabric-api 0.46.4, 0.46.3, 0.46.1, 0.45.0 before Waoweens made the connection with fabric-loader 0.13.0 ^^'
so long as loader 0.12.12 is usable i'm okay with it , for the time being i doubt any mod would require loader 0.13.0 
Good luck x)

**Comment by celophys** [comment]
Ok thanks!

**Comment by Ced-Sharp** [comment]
I can also confirm this issue is related to fabric 0.13.0, the previous 0.12.12 works as expected:
![image](https://user-images.githubusercontent.com/56606410/152567955-6d5924c3-795b-4cce-bb6f-1306687afd15.png)


I changed the setting to use scrolling instead of pagination, and realized the REI is working perfectly (I see the scrollbar and can scroll)!

The only issue is that the image of the items is not rendering. If I put my mouse randomly where items should be and hit R, I actually see a recipe show up!

So REI seems to be working as expected. The bug seems to be only items not rendering.

![image](https://user-images.githubusercontent.com/56606410/152567006-56f40d55-cb2b-4813-b27b-2bad9adcb3d7.png)

In the screenshot above, you can see recipe screen works;
You can see a scrollbar on the right, and the weird bars are probably item durability/damage.

NOTE: All buttons and the search field are missing. Probably due to the same reason items are not rendering?

**Comment by shedaniel** [comment]
A fix has been deployed to architectury api that should fix this issue now!
