### ISSUE TITLE
[Bug] REI and Architectury crash

### ISSUE THREAD

**Issue by Sunconure11** [shedaniel/RoughlyEnoughItems#769]
### What happened?

Random crash out of the blue, seemed to blame REI and Architectury

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://pastebin.com/eaLDPCAG
```

**Comment by shedaniel** [comment]
Caused by MultiBeds

**Comment by ShetiPhian** [comment]
@shedaniel You've likely seen this error from several mods: 
```Cannot invoke "java.util.List.isEmpty()" because "quads" is null```

This is an issue with Sodium breaking the Fabric Rendering API.
Users must install Indium to fix it.

**Comment by Sunconure11** [comment]
But I have both…

**Comment by shedaniel** [comment]
> @shedaniel You've likely seen this error from several mods: 
> 
> ```Cannot invoke "java.util.List.isEmpty()" because "quads" is null```
> 
> 
> 
> This is an issue with Sodium breaking the Fabric Rendering API.
> 
> Users must install Indium to fix it.

Honestly, I don't really care enough to look at these issues more, I am bombarded by many of these crashes caused by other mods but reported to REI, so I don't have time to understand and provide suggestions on how to fix every users' issue. In this case I would think that returning null in your model could be replaced by a throw, as I have seen a lot of NPEs already and I don't really have a brain anymore seeing all these NPEs when REI tries to render items
