### ISSUE TITLE
[Bug?] Can't use left and right click to check recipes anymore?

### ISSUE THREAD

**Issue by HacoKavanah** [shedaniel/RoughlyEnoughItems#861]
### What happened?

Did you guys change this? Didn't see it in the changelog.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
-
```

### Anything else?

-

**Comment by shedaniel** [comment]
Yes this would be a bug

**Comment by mwforrest7** [comment]
@shedaniel 

I saw this bug was fixed and verified this for myself, but in doing so I've discovered what I think is a variation on this bug:

1. Clicking on an item in REI now shows the recipe (thanks to this fix)
2. However, left or right clicking on one of the ingredients in the resulting recipe has the same issue as this bug.

**Comment by FreeFull** [comment]
one last variation of the bug, it seems like clicking on items that have been favourited (in the left pane) doesn't work

**Comment by shedaniel** [comment]
i am die
