### ISSUE TITLE
[Bug] Game Hang When Opening Tag Tab

### ISSUE THREAD

**Issue by ardissaps** [shedaniel/RoughlyEnoughItems#963]
### What happened?

Superslow when opening recipe especially when Tag Tab is first displayed.
![image](https://user-images.githubusercontent.com/82106625/176066846-eff42796-9a78-403e-8e4f-27e719e4ba59.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://paste.atlauncher.com/view/8c4d763c-a41e-43e3-8fc0-b7938e9d214c
```

**Comment by MaxNeedsSnacks** [comment]
I'm assuming this has to do with the fact that tag entries are not properly culled at the moment, so **every element of the tree is being rendered all the time**. I'd expect that to be something like the "mineable with pickaxe" tag that's part of vanilla now, and since MC item rendering is *abysmally slow*, i could imagine that having to render 5k+ items at the same time causes this kind of lag

**Comment by Evoloxi** [comment]
This really is an annoying bug, especially in huge modpacks. For me it doesn't quite freeze, but performance does drop to unbearable levels when viewing certain tags.

**Comment by ardissaps** [comment]
Thanks for the fix!
